#!/usr/bin/env node
/**
 * init-brand — inject Kimi brand tokens into an existing project.
 *
 * Usage:
 *   node scripts/init-brand.mjs [targetDir] [--format css|tailwind|json|all] [--force]
 *
 * Examples:
 *   node scripts/init-brand.mjs ./my-site --format css
 *   node scripts/init-brand.mjs ./my-app --format tailwind
 *   node scripts/init-brand.mjs . --format all
 *
 * Behaviour:
 *   - Never overwrites an existing file unless --force is passed.
 *   - Always prints a short brand-compliance checklist.
 *   - Reads tokens from assets/kimi-brand-tokens.json (single source of truth).
 *
 * Source: https://www.kimi.com/resources/kimi-brand
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const TOKENS_PATH = path.join(ROOT, 'assets', 'kimi-brand-tokens.json');
const THEME_PATH = path.join(ROOT, 'assets', 'kimi-brand-theme.css');
const WORDMARK_PATH = path.join(ROOT, 'assets', 'kimi-wordmark.svg');

// ---------- args ----------
const argv = process.argv.slice(2);
const flags = new Set(argv.filter((a) => a.startsWith('--')));
const positional = argv.filter((a) => !a.startsWith('--'));
const targetDir = path.resolve(process.cwd(), positional[0] || '.');

let format = 'all';
const fmtArg = argv.find((a) => a.startsWith('--format='));
if (fmtArg) format = fmtArg.split('=')[1];
else {
  const i = argv.indexOf('--format');
  if (i !== -1 && argv[i + 1] && !argv[i + 1].startsWith('--')) format = argv[i + 1];
}

const force = flags.has('--force');
const validFormats = ['css', 'tailwind', 'json', 'all'];

if (!validFormats.includes(format)) {
  console.error(`✗ Invalid --format "${format}". Expected one of: ${validFormats.join(', ')}`);
  process.exit(1);
}
if (fs.existsSync(targetDir) && !fs.statSync(targetDir).isDirectory()) {
  console.error(`✗ Target path exists but is not a directory: ${targetDir}`);
  process.exit(1);
}
fs.mkdirSync(targetDir, { recursive: true });

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf8'));
const written = [];
const skipped = [];

function writeFile(relPath, content) {
  const abs = path.join(targetDir, relPath);
  if (fs.existsSync(abs) && !force) {
    skipped.push(relPath);
    return;
  }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, 'utf8');
  written.push(relPath);
}

// ---------- 1. CSS ----------
if (format === 'css' || format === 'all') {
  writeFile('kimi-brand-theme.css', fs.readFileSync(THEME_PATH, 'utf8'));
}

// ---------- 2. Tailwind ----------
if (format === 'tailwind' || format === 'all') {
  const c = tokens.color;
  const spacing = Object.fromEntries(tokens.space.scale.map((n) => [String(n), String(n) + 'px']));
  const tw = `/** Tailwind config — Kimi brand palette. Generated by init-brand.mjs. */
module.exports = {
  theme: {
    extend: {
      colors: {
        kimi: {
          blue: '${c.brand.blue.value}',
          'deep-blue': '${c.brand.deepBlue.value}',
          azure: '${c.brand.azure.value}',
          sky: '${c.brand.sky.value}',
          'electric-cyan': '${c.brand.electricCyan.value}',
          lavender: '${c.accent.lavender.value}',
          blush: '${c.accent.blush.value}',
          mint: '${c.accent.mint.value}',
          citron: '${c.accent.citron.value}',
          ink: '${c.neutral.ink.value}',
          slate: '${c.neutral.slate.value}',
          graphite: '${c.neutral.graphite.value}',
          silver: '${c.neutral.silver.value}',
          mist: '${c.neutral.mist.value}',
          white: '${c.neutral.white.value}',
          'ink-border': '${c.derived.inkBorder.value}',
          'ink-raised': '${c.derived.inkRaised.value}'
        }
      },
      fontFamily: {
        sans: ['Inter', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'SF Mono', 'Cascadia Code', 'Consolas', 'monospace'],
        serif: ['Sentient', 'Noto Serif SC', 'Source Han Serif SC', 'Lora', 'Georgia', 'serif']
      },
      spacing: ${JSON.stringify(spacing, null, 8).replace(/\n/g, '\n      ')},
      borderRadius: {
        control: '${tokens.radius.control}px',
        card: '${tokens.radius.card}px',
        container: '${tokens.radius.container}px'
      }
    }
  }
};
`;
  writeFile('tailwind.kimi-brand.js', tw);
}

// ---------- 3. JSON ----------
if (format === 'json' || format === 'all') {
  writeFile('kimi-brand-tokens.json', JSON.stringify(tokens, null, 2) + '\n');
}

// ---------- 4. Wordmark (only when css/all, it's a web asset) ----------
if (format === 'css' || format === 'all') {
  writeFile('kimi-wordmark.svg', fs.readFileSync(WORDMARK_PATH, 'utf8'));
}

// ---------- report ----------
console.log('\nKimi brand tokens → ' + targetDir + '\n');
if (written.length) {
  written.forEach((f) => console.log('  ✓ created  ' + f));
}
if (skipped.length) {
  skipped.forEach((f) => console.log('  – skipped  ' + f + '  (exists; use --force to overwrite)'));
}
if (!written.length && !skipped.length) {
  console.log('  nothing to do');
}

console.log(`
Next steps
  1. Load the fonts: Inter (body) + Geist Mono (code/metrics). Sentient is commercial — use a licensed copy or the documented serif fallback.
  2. Link text on light backgrounds: use --kimi-deep-blue (#002F5B). Brand blue on white is 3.94:1 and fails AA for body text.
  3. Filled buttons with small text: fill with #002F5B, not #007CFF, to stay AA.
  4. Charts: neutral gray base, electric blue for the one metric that matters. Never distort the data.
  5. Logo: do not modify, recolor, stretch, or add effects — and get written permission (hi@moonshot.ai) before any commercial use.

Full spec: ${tokens.source.brandGuidelinesZh}
`);
